name: CI Windows

on:
  push:
  pull_request:

jobs:

# ------------------------------------------------------------
  test:
    runs-on: windows-2022

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Clone and build GTest
      uses: ./.github/actions/build-gtest
    - name: Compile Tests for Windows x86
      run: |
        cmake -B %GITHUB_WORKSPACE%\build_test -G "Visual Studio 17 2022" -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -DGTEST_ROOT=%GITHUB_WORKSPACE%\googletest\install -S %GITHUB_WORKSPACE%/simpleble -DSIMPLEBLE_TEST=ON
        cmake --build %GITHUB_WORKSPACE%\build_test --config Release --parallel 4
        %GITHUB_WORKSPACE%\build_test\bin\Release\simpleble_test.exe
      shell: cmd

  cpp-release-windows:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        arch: [Win32, x64]
        type: [shared, static]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Compile SimpleBLE
        shell: cmd
        run: |

          if "${{ matrix.type }}" == "shared" (
            set BUILD_SHARED_LIBS=ON
          ) else (
            set BUILD_SHARED_LIBS=OFF
          )

          cmake -B %GITHUB_WORKSPACE%\build -G "Visual Studio 17 2022" -A ${{ matrix.arch }} -DCMAKE_SYSTEM_VERSION="10.0.19041.0" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -S %GITHUB_WORKSPACE%/simpleble
          cmake --build %GITHUB_WORKSPACE%\build --config Release --parallel 4
          cmake --install %GITHUB_WORKSPACE%\build --prefix %GITHUB_WORKSPACE%\build\install

          mkdir -p $GITHUB_WORKSPACE\artifacts
          7z a -tzip %GITHUB_WORKSPACE%\artifacts\simpleble_${{ matrix.type }}_windows-${{ matrix.arch }}.zip %GITHUB_WORKSPACE%\build\install

      - name: Upload binaries to job
        uses: actions/upload-artifact@v3
        with:
          name: simpleble_${{ matrix.type }}_windows-${{ matrix.arch }}
          path: artifacts/simpleble_${{ matrix.type }}_windows-${{ matrix.arch }}.zip

# rust:
  #   runs-on: windows-2022

  #   strategy:
  #     fail-fast: false
  #     max-parallel: 4
  #     matrix:
  #       arch: [Win32, x64]
  #       sdk: ["10.0.19041.0", "10.0.22000.0"]

  #   steps:
  #   - name: Clone Repository
  #     uses: actions/checkout@v3
  examples:
    runs-on: windows-2022

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Compile Examples
      run: |
        cmake -B %GITHUB_WORKSPACE%\build -G "Visual Studio 17 2022" -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -S %GITHUB_WORKSPACE%/examples/simpleble
        cmake --build %GITHUB_WORKSPACE%\build --config Release --parallel 4
      shell: cmd
